<a href="https://colab.research.google.com/github/lovnishverma/Python-Getting-Started/blob/main/got_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy**

# Install NumPy

In [1]:
!pip install numpy -q

# Import NumPy

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [4]:
arr[3]

np.int64(4)

In [5]:
arr[-1]

np.int64(5)

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr[1:4] # start:stop

array([2, 3, 4])

In [8]:
arr = np.array([1, 2, 3, 4, 5,6,7,8,9,10])

In [9]:
arr[::2] # start:stop:step(jump)

array([1, 3, 5, 7, 9])

In [10]:
arr.ndim

1

In [11]:
arr.shape

(10,)

In [12]:
arr.dtype

dtype('int64')

In [13]:
# 2d array operation

arr2d = np.array([[1, 2, 3, 4,5,8], [5,6,7,8,9,10]])

arr2d

array([[ 1,  2,  3,  4,  5,  8],
       [ 5,  6,  7,  8,  9, 10]])

In [14]:
arr2d.ndim

2

In [15]:
arr2d.shape

(2, 6)

In [16]:
arr2d

array([[ 1,  2,  3,  4,  5,  8],
       [ 5,  6,  7,  8,  9, 10]])

In [17]:
# indexing in 2d ndarray

arr2d[:-1]

array([[1, 2, 3, 4, 5, 8]])

In [18]:
arr2d

array([[ 1,  2,  3,  4,  5,  8],
       [ 5,  6,  7,  8,  9, 10]])

In [19]:
#slicing
arr2d[1, 3] # rows, columns

np.int64(8)

In [20]:
arr2d

array([[ 1,  2,  3,  4,  5,  8],
       [ 5,  6,  7,  8,  9, 10]])

In [21]:
arr2d[:,-1] # rows, columns

array([ 8, 10])

In [22]:
arr2d[:,4] # rows, columns

array([5, 9])

In [23]:
arr2d[:,5] # rows, columns

array([ 8, 10])

In [24]:
arr2d

array([[ 1,  2,  3,  4,  5,  8],
       [ 5,  6,  7,  8,  9, 10]])

In [25]:
arr2d[:,:-1]

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [26]:
# 3d array operation

arr3d = np.array([[[1, 2, 3, 4,5,8], [5,6,7,8,9,10], [11,12,13,14,15,16]]])

arr3d

array([[[ 1,  2,  3,  4,  5,  8],
        [ 5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16]]])

In [27]:
arr3d.ndim

3

In [28]:

rand_arr = np.random.randint(1,7)  # Random numbers between 0 and 1
# np.random.seed(1)
print(rand_arr)

1


# Pandas

In [29]:
import pandas as pd

In [30]:
# series

ser = pd.Series([1, 2, 3, 4, 5])

ser

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [31]:
dictionary = {'Name': ['Lovnish', 'Ankit', 'Ram', 'Sita'],
              'Age': [20, 19, 22, 21]}

In [32]:
df = pd.DataFrame(dictionary)

In [33]:
df

Name  Age
0  Lovnish   20
1    Ankit   19
2      Ram   22
3     Sita   21

In [35]:
df = pd.read_csv("https://raw.githubusercontent.com/princevermagps/datesets/refs/heads/main/data.csv")

df.head()

Name  Age  Marks
0   Ram   25     88
1  Sham   27     98
2  Sita   46     75