<a href="https://colab.research.google.com/github/lovnishverma/Python-Getting-Started/blob/main/lambrin_day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [157]:
#import google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [158]:
# !pip install pandas

In [159]:
import pandas as pd

In [180]:
#load dataset form google drive
df = pd.read_csv("/content/drive/MyDrive/datasets/testdata.csv")

0     False
1     False
2     False
3     False
4     False
      ...  
75    False
76    False
77    False
78    False
79    False
Length: 80, dtype: bool

In [161]:
df

rank discipline  phd  service     sex    salary
0        Prof          B   56     49.0    Male  186960.0
1        Prof          A   12      6.0    Male   93000.0
2         NaN          A   23     20.0    Male  110515.0
3        Prof          A   40     31.0     NaN  131205.0
4        Prof          B   20      NaN    Male  104800.0
..        ...        ...  ...      ...     ...       ...
75       Prof          B   18     10.0  Female  105450.0
76  AssocProf          B   19      6.0  Female  104542.0
77       Prof          B   17     17.0  Female  124312.0
78       Prof          A   28     14.0  Female  109954.0
79       Prof          A   23     15.0  Female  109646.0

[80 rows x 6 columns]

In [162]:
df.head(15)

rank discipline  phd  service   sex    salary
0        Prof          B   56     49.0  Male  186960.0
1        Prof          A   12      6.0  Male   93000.0
2         NaN          A   23     20.0  Male  110515.0
3        Prof          A   40     31.0   NaN  131205.0
4        Prof          B   20      NaN  Male  104800.0
5        Prof          A   20     20.0  Male  122400.0
6   AssocProf          A   20     17.0  Male   81285.0
7        Prof          A   18     18.0  Male  126300.0
8        Prof          A   18     18.0  Male  126300.0
9        Prof          A   29     19.0  Male   94350.0
10       Prof          A   51     51.0  Male   57800.0
11       Prof          B   39     33.0  Male  128250.0
12       Prof          B   23     23.0  Male  134778.0
13   AsstProf          B    1      0.0  Male   88000.0
14   AsstProf          B    1      0.0  Male   88000.0

In [163]:
df.tail()

rank discipline  phd  service     sex    salary
75       Prof          B   18     10.0  Female  105450.0
76  AssocProf          B   19      6.0  Female  104542.0
77       Prof          B   17     17.0  Female  124312.0
78       Prof          A   28     14.0  Female  109954.0
79       Prof          A   23     15.0  Female  109646.0

In [164]:
df.describe()

phd    service         salary
count  80.000000  79.000000      79.000000
mean   19.450000  14.860759  107315.886076
std    12.516217  12.179990   27596.271520
min     1.000000   0.000000   57800.000000
25%    10.000000   4.500000   88000.000000
50%    18.000000  14.000000  104542.000000
75%    27.250000  20.500000  126300.000000
max    56.000000  51.000000  186960.000000

In [165]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   rank        79 non-null     object 
 1   discipline  79 non-null     object 
 2   phd         80 non-null     int64  
 3   service     79 non-null     float64
 4   sex         79 non-null     object 
 5   salary      79 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 3.9+ KB


In [167]:
df

rank discipline  phd  service     sex    salary
0        Prof          B   56     49.0    Male  186960.0
1        Prof          A   12      6.0    Male   93000.0
2         NaN          A   23     20.0    Male  110515.0
3        Prof          A   40     31.0     NaN  131205.0
4        Prof          B   20      NaN    Male  104800.0
..        ...        ...  ...      ...     ...       ...
75       Prof          B   18     10.0  Female  105450.0
76  AssocProf          B   19      6.0  Female  104542.0
77       Prof          B   17     17.0  Female  124312.0
78       Prof          A   28     14.0  Female  109954.0
79       Prof          A   23     15.0  Female  109646.0

[80 rows x 6 columns]

In [168]:
df.shape

(80, 6)

In [169]:
df.isnull().sum()

rank          1
discipline    1
phd           0
service       1
sex           1
salary        1
dtype: int64

In [170]:
df

rank discipline  phd  service     sex    salary
0        Prof          B   56     49.0    Male  186960.0
1        Prof          A   12      6.0    Male   93000.0
2         NaN          A   23     20.0    Male  110515.0
3        Prof          A   40     31.0     NaN  131205.0
4        Prof          B   20      NaN    Male  104800.0
..        ...        ...  ...      ...     ...       ...
75       Prof          B   18     10.0  Female  105450.0
76  AssocProf          B   19      6.0  Female  104542.0
77       Prof          B   17     17.0  Female  124312.0
78       Prof          A   28     14.0  Female  109954.0
79       Prof          A   23     15.0  Female  109646.0

[80 rows x 6 columns]

In [171]:
#filling the missing value
# df['service'].fillna(df['service'].mean(),inplace=True) #average
# df['service'].fillna(value=25, inplace=True)
df

rank discipline  phd  service     sex    salary
0        Prof          B   56     49.0    Male  186960.0
1        Prof          A   12      6.0    Male   93000.0
2         NaN          A   23     20.0    Male  110515.0
3        Prof          A   40     31.0     NaN  131205.0
4        Prof          B   20      NaN    Male  104800.0
..        ...        ...  ...      ...     ...       ...
75       Prof          B   18     10.0  Female  105450.0
76  AssocProf          B   19      6.0  Female  104542.0
77       Prof          B   17     17.0  Female  124312.0
78       Prof          A   28     14.0  Female  109954.0
79       Prof          A   23     15.0  Female  109646.0

[80 rows x 6 columns]

In [172]:
#droping the missing values
# df.dropna(inplace=True) #by default it will take axis=0 if you will not give the axis parameter
# df.dropna(inplace=True, axis=0) #drop rows with the missing values
# df

In [173]:
# df.dropna(inplace=True, axis=1) #drop columns with the missing values
# df

In [174]:
df

rank discipline  phd  service     sex    salary
0        Prof          B   56     49.0    Male  186960.0
1        Prof          A   12      6.0    Male   93000.0
2         NaN          A   23     20.0    Male  110515.0
3        Prof          A   40     31.0     NaN  131205.0
4        Prof          B   20      NaN    Male  104800.0
..        ...        ...  ...      ...     ...       ...
75       Prof          B   18     10.0  Female  105450.0
76  AssocProf          B   19      6.0  Female  104542.0
77       Prof          B   17     17.0  Female  124312.0
78       Prof          A   28     14.0  Female  109954.0
79       Prof          A   23     15.0  Female  109646.0

[80 rows x 6 columns]

In [175]:
# df['sex'].fillna(value="Male", inplace=True)

In [176]:
from sklearn.preprocessing import LabelEncoder

In [177]:
encoder = LabelEncoder()

# df['sex'] = encoder.fit_transform(df['sex'])
# df

In [178]:
df.shape

(80, 6)

In [179]:
#find duplicate values in dataset
# df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...  
75    False
76    False
77    False
78    False
79    False
Length: 80, dtype: bool

In [181]:
#droping duplacates values
df.drop_duplicates(inplace=True)

In [182]:
df.shape

(78, 6)

#NUMPY

In [188]:
import numpy as np

In [189]:
arr1d = np.array([1,2,3,4,5])

In [190]:
print(arr1d)

[1 2 3 4 5]


In [191]:

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [192]:
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3d)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [194]:
arr2d.ndim

2

In [195]:
arr2d.shape #rows, columns

(2, 3)

In [196]:
arr2d.size

6

In [197]:
arr2d.dtype

dtype('int64')

In [199]:
rand_arr = np.random.rand(1, 3)  # Random numbers between 0 and 1
print(rand_arr)

[[0.58583093 0.63740952 0.37760352]]


In [223]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[-1])   #start:stop:jump

5


In [217]:

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d


array([[1, 2, 3],
       [4, 5, 6]])

In [227]:
#slicing 2d array
print(arr2d[:,-1])

[3 6]


In [226]:
print(arr2d[0:2,0:2])

[[1 2]
 [4 5]]


In [228]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # Element-wise addition
print(a - b)  # Element-wise subtraction
print(a * b)  # Element-wise multiplication
print(a / b)  # Element-wise division
print(a ** 2) # Square of each element

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [229]:

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))  # Sum of elements
print(np.mean(arr)) # Mean (average)
print(np.max(arr))  # Maximum element
print(np.min(arr))  # Minimum element
print(np.std(arr))  # Standard deviation

15
3.0
5
1
1.4142135623730951


In [235]:
#load dataset form google drive
df = pd.read_csv("/content/drive/MyDrive/datasets/testdata.csv")

In [236]:
df

rank discipline  phd  service     sex    salary
0        Prof          B   56     49.0    Male  186960.0
1        Prof          A   12      6.0    Male   93000.0
2         NaN          A   23     20.0    Male  110515.0
3        Prof          A   40     31.0     NaN  131205.0
4        Prof          B   20      NaN    Male  104800.0
..        ...        ...  ...      ...     ...       ...
75       Prof          B   18     10.0  Female  105450.0
76  AssocProf          B   19      6.0  Female  104542.0
77       Prof          B   17     17.0  Female  124312.0
78       Prof          A   28     14.0  Female  109954.0
79       Prof          A   23     15.0  Female  109646.0

[80 rows x 6 columns]

In [238]:
a = df['salary']
a

0     186960.0
1      93000.0
2     110515.0
3     131205.0
4     104800.0
        ...   
75    105450.0
76    104542.0
77    124312.0
78    109954.0
79    109646.0
Name: salary, Length: 80, dtype: float64

In [239]:
b = df[['rank',	'discipline',	'phd',	'service',	'sex'	]]
b

rank discipline  phd  service     sex
0        Prof          B   56     49.0    Male
1        Prof          A   12      6.0    Male
2         NaN          A   23     20.0    Male
3        Prof          A   40     31.0     NaN
4        Prof          B   20      NaN    Male
..        ...        ...  ...      ...     ...
75       Prof          B   18     10.0  Female
76  AssocProf          B   19      6.0  Female
77       Prof          B   17     17.0  Female
78       Prof          A   28     14.0  Female
79       Prof          A   23     15.0  Female

[80 rows x 5 columns]