<a href="https://colab.research.google.com/github/lovnishverma/Python-Getting-Started/blob/main/lambrin_day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [241]:
#import google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [242]:
# !pip install pandas

In [243]:
import pandas as pd

In [244]:
#load dataset form google drive
df = pd.read_csv("/content/drive/MyDrive/datasets/testdata.csv")

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  \
0          505701            6548         21-May-06     1     0     0     0   
1          500633            6584         02-Jun-06     0     0     0     0   
2          506945            6582         10-Aug-06     0     0     0     0   
3          497447            6551         27-Aug-06     0     0     0     0   
4          496446            6533         19-Sep-06     0     0     0     0   
...           ...             ...               ...   ...   ...   ...   ...   
35244      507261            6525         13-Apr-06    12     2     0     0   
35245      513607            6551         03-Nov-06     0     0     0     0   
35246      498160            6584         17-Jun-06     0     0     0     0   
35247      502444            6567         13-Jan-07     0     0     0     0   
35248      523811            6584         16-Jun-06     4     3     0     2   

       Var5  
0         2  
1         0  
2         0  
3         0  
4         0  
...     ...  
35244     6  
35245     0  
35246     0  
35247     0  
35248     4  

[35249 rows x 8 columns]

In [245]:
df

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  \
0          505701            6548         21-May-06     1     0     0     0   
1          500633            6584         02-Jun-06     0     0     0     0   
2          506945            6582         10-Aug-06     0     0     0     0   
3          497447            6551         27-Aug-06     0     0     0     0   
4          496446            6533         19-Sep-06     0     0     0     0   
...           ...             ...               ...   ...   ...   ...   ...   
35244      507261            6525         13-Apr-06    12     2     0     0   
35245      513607            6551         03-Nov-06     0     0     0     0   
35246      498160            6584         17-Jun-06     0     0     0     0   
35247      502444            6567         13-Jan-07     0     0     0     0   
35248      523811            6584         16-Jun-06     4     3     0     2   

       Var5  
0         2  
1         0  
2         0  
3         0  
4         0  
...     ...  
35244     6  
35245     0  
35246     0  
35247     0  
35248     4  

[35249 rows x 8 columns]

In [246]:
df.head(15)

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  Var5
0       505701            6548         21-May-06     1     0     0     0     2
1       500633            6584         02-Jun-06     0     0     0     0     0
2       506945            6582         10-Aug-06     0     0     0     0     0
3       497447            6551         27-Aug-06     0     0     0     0     0
4       496446            6533         19-Sep-06     0     0     0     0     0
5       494067            6548         19-Jul-06     0     0     0     0     0
6       498974            6574         29-Jun-06     0     0     0     0     0
7       525212            6567         01-Feb-07     0     0     0     0     0
8       507387            6583         03-Aug-06     0     0     0     0     0
9       517714            6573         18-Sep-06     0     0     0     0     0
10      500798            6572         06-Jul-06     0     0     0     0     0
11      489618            6551         26-Aug-06     0     0     0     0     0
12      495624            6582         13-Jun-06     0     0     0     0     0
13      488974            6566         04-Mar-06     0     0     0     0     0
14      523022            6573         01-Sep-06     3     0     0     0     0

In [247]:
df.tail()

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  \
35244      507261            6525         13-Apr-06    12     2     0     0   
35245      513607            6551         03-Nov-06     0     0     0     0   
35246      498160            6584         17-Jun-06     0     0     0     0   
35247      502444            6567         13-Jan-07     0     0     0     0   
35248      523811            6584         16-Jun-06     4     3     0     2   

       Var5  
35244     6  
35245     0  
35246     0  
35247     0  
35248     4

In [248]:
df.describe()

Patient_ID  Health_Camp_ID          Var1          Var2  \
count   35249.000000    35249.000000  35249.000000  35249.000000   
mean   507020.926863     6568.160373      0.819201      0.253312   
std     12478.669016       13.212263      8.298817      3.984690   
min    485678.000000     6525.000000      0.000000      0.000000   
25%    496203.000000     6556.000000      0.000000      0.000000   
50%    507018.000000     6568.000000      0.000000      0.000000   
75%    517869.000000     6582.000000      0.000000      0.000000   
max    528657.000000     6584.000000    344.000000    181.000000   

               Var3          Var4          Var5  
count  35249.000000  35249.000000  35249.000000  
mean       0.000567      0.041845      0.258163  
std        0.023814      0.268826      1.311230  
min        0.000000      0.000000      0.000000  
25%        0.000000      0.000000      0.000000  
50%        0.000000      0.000000      0.000000  
75%        0.000000      0.000000      0.000000  
max        1.000000      8.000000     34.000000

In [249]:
df.columns

Index(['Patient_ID', 'Health_Camp_ID', 'Registration_Date', 'Var1', 'Var2',
       'Var3', 'Var4', 'Var5'],
      dtype='object')

In [250]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35249 entries, 0 to 35248
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Patient_ID         35249 non-null  int64 
 1   Health_Camp_ID     35249 non-null  int64 
 2   Registration_Date  35249 non-null  object
 3   Var1               35249 non-null  int64 
 4   Var2               35249 non-null  int64 
 5   Var3               35249 non-null  int64 
 6   Var4               35249 non-null  int64 
 7   Var5               35249 non-null  int64 
dtypes: int64(7), object(1)
memory usage: 2.2+ MB


In [251]:
df

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  \
0          505701            6548         21-May-06     1     0     0     0   
1          500633            6584         02-Jun-06     0     0     0     0   
2          506945            6582         10-Aug-06     0     0     0     0   
3          497447            6551         27-Aug-06     0     0     0     0   
4          496446            6533         19-Sep-06     0     0     0     0   
...           ...             ...               ...   ...   ...   ...   ...   
35244      507261            6525         13-Apr-06    12     2     0     0   
35245      513607            6551         03-Nov-06     0     0     0     0   
35246      498160            6584         17-Jun-06     0     0     0     0   
35247      502444            6567         13-Jan-07     0     0     0     0   
35248      523811            6584         16-Jun-06     4     3     0     2   

       Var5  
0         2  
1         0  
2         0  
3         0  
4         0  
...     ...  
35244     6  
35245     0  
35246     0  
35247     0  
35248     4  

[35249 rows x 8 columns]

In [252]:
df.shape

(35249, 8)

In [253]:
df.isnull().sum()

Patient_ID           0
Health_Camp_ID       0
Registration_Date    0
Var1                 0
Var2                 0
Var3                 0
Var4                 0
Var5                 0
dtype: int64

In [254]:
df

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  \
0          505701            6548         21-May-06     1     0     0     0   
1          500633            6584         02-Jun-06     0     0     0     0   
2          506945            6582         10-Aug-06     0     0     0     0   
3          497447            6551         27-Aug-06     0     0     0     0   
4          496446            6533         19-Sep-06     0     0     0     0   
...           ...             ...               ...   ...   ...   ...   ...   
35244      507261            6525         13-Apr-06    12     2     0     0   
35245      513607            6551         03-Nov-06     0     0     0     0   
35246      498160            6584         17-Jun-06     0     0     0     0   
35247      502444            6567         13-Jan-07     0     0     0     0   
35248      523811            6584         16-Jun-06     4     3     0     2   

       Var5  
0         2  
1         0  
2         0  
3         0  
4         0  
...     ...  
35244     6  
35245     0  
35246     0  
35247     0  
35248     4  

[35249 rows x 8 columns]

In [255]:
#filling the missing value
# df['service'].fillna(df['service'].mean(),inplace=True) #average
# df['service'].fillna(value=25, inplace=True)
df

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  \
0          505701            6548         21-May-06     1     0     0     0   
1          500633            6584         02-Jun-06     0     0     0     0   
2          506945            6582         10-Aug-06     0     0     0     0   
3          497447            6551         27-Aug-06     0     0     0     0   
4          496446            6533         19-Sep-06     0     0     0     0   
...           ...             ...               ...   ...   ...   ...   ...   
35244      507261            6525         13-Apr-06    12     2     0     0   
35245      513607            6551         03-Nov-06     0     0     0     0   
35246      498160            6584         17-Jun-06     0     0     0     0   
35247      502444            6567         13-Jan-07     0     0     0     0   
35248      523811            6584         16-Jun-06     4     3     0     2   

       Var5  
0         2  
1         0  
2         0  
3         0  
4         0  
...     ...  
35244     6  
35245     0  
35246     0  
35247     0  
35248     4  

[35249 rows x 8 columns]

In [256]:
#droping the missing values
# df.dropna(inplace=True) #by default it will take axis=0 if you will not give the axis parameter
# df.dropna(inplace=True, axis=0) #drop rows with the missing values
# df

In [257]:
# df.dropna(inplace=True, axis=1) #drop columns with the missing values
# df

In [258]:
df

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  \
0          505701            6548         21-May-06     1     0     0     0   
1          500633            6584         02-Jun-06     0     0     0     0   
2          506945            6582         10-Aug-06     0     0     0     0   
3          497447            6551         27-Aug-06     0     0     0     0   
4          496446            6533         19-Sep-06     0     0     0     0   
...           ...             ...               ...   ...   ...   ...   ...   
35244      507261            6525         13-Apr-06    12     2     0     0   
35245      513607            6551         03-Nov-06     0     0     0     0   
35246      498160            6584         17-Jun-06     0     0     0     0   
35247      502444            6567         13-Jan-07     0     0     0     0   
35248      523811            6584         16-Jun-06     4     3     0     2   

       Var5  
0         2  
1         0  
2         0  
3         0  
4         0  
...     ...  
35244     6  
35245     0  
35246     0  
35247     0  
35248     4  

[35249 rows x 8 columns]

In [259]:
# df['sex'].fillna(value="Male", inplace=True)

In [260]:
from sklearn.preprocessing import LabelEncoder

In [261]:
encoder = LabelEncoder()

# df['sex'] = encoder.fit_transform(df['sex'])
# df

In [262]:
df.shape

(35249, 8)

In [263]:
#find duplicate values in dataset
# df.duplicated()

In [264]:
#droping duplacates values
df.drop_duplicates(inplace=True)

In [265]:
df.shape

(35249, 8)

In [266]:
# Save to CSV file
df.to_csv('mycleanned_data.csv', index=False)

In [288]:
#saving csv file using pandas
df.to_csv('mycleanned_data.csv', index=False) #write index=False to get rid of first id column (0,1,2,3,4) it's useless

In [289]:
#saving csv file to google driveusing pandas
# df.to_csv('/content/drive/MyDrive/datasets/mycleanned_data.csv', index=False)

#NUMPY

In [267]:
import numpy as np

In [268]:
arr1d = np.array([1,2,3,4,5])

In [269]:
print(arr1d)

[1 2 3 4 5]


In [270]:

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [271]:
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3d)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [272]:
arr2d.ndim

2

In [273]:
arr2d.shape #rows, columns

(2, 3)

In [274]:
arr2d.size

6

In [275]:
arr2d.dtype

dtype('int64')

In [276]:
rand_arr = np.random.rand(1, 3)  # Random numbers between 0 and 1
print(rand_arr)

[[0.9444554  0.70239679 0.90877689]]


In [277]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[-1])   #start:stop:jump

5


In [278]:

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d


array([[1, 2, 3],
       [4, 5, 6]])

In [279]:
#slicing 2d array
print(arr2d[:,-1])

[3 6]


In [280]:
print(arr2d[0:2,0:2])

[[1 2]
 [4 5]]


In [281]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # Element-wise addition
print(a - b)  # Element-wise subtraction
print(a * b)  # Element-wise multiplication
print(a / b)  # Element-wise division
print(a ** 2) # Square of each element

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [282]:

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))  # Sum of elements
print(np.mean(arr)) # Mean (average)
print(np.max(arr))  # Maximum element
print(np.min(arr))  # Minimum element
print(np.std(arr))  # Standard deviation

15
3.0
5
1
1.4142135623730951


In [283]:
#load dataset form google drive
df = pd.read_csv("/content/drive/MyDrive/datasets/testdata.csv")

In [284]:
df

rank discipline  phd  service     sex    salary
0        Prof          B   56     49.0    Male  186960.0
1        Prof          A   12      6.0    Male   93000.0
2         NaN          A   23     20.0    Male  110515.0
3        Prof          A   40     31.0     NaN  131205.0
4        Prof          B   20      NaN    Male  104800.0
..        ...        ...  ...      ...     ...       ...
75       Prof          B   18     10.0  Female  105450.0
76  AssocProf          B   19      6.0  Female  104542.0
77       Prof          B   17     17.0  Female  124312.0
78       Prof          A   28     14.0  Female  109954.0
79       Prof          A   23     15.0  Female  109646.0

[80 rows x 6 columns]

pandas slicing using features

In [285]:
a = df['salary']
a

0     186960.0
1      93000.0
2     110515.0
3     131205.0
4     104800.0
        ...   
75    105450.0
76    104542.0
77    124312.0
78    109954.0
79    109646.0
Name: salary, Length: 80, dtype: float64

In [286]:
b = df[['rank',	'discipline',	'phd',	'service',	'sex'	]]
b

rank discipline  phd  service     sex
0        Prof          B   56     49.0    Male
1        Prof          A   12      6.0    Male
2         NaN          A   23     20.0    Male
3        Prof          A   40     31.0     NaN
4        Prof          B   20      NaN    Male
..        ...        ...  ...      ...     ...
75       Prof          B   18     10.0  Female
76  AssocProf          B   19      6.0  Female
77       Prof          B   17     17.0  Female
78       Prof          A   28     14.0  Female
79       Prof          A   23     15.0  Female

[80 rows x 5 columns]