<a href="https://colab.research.google.com/github/lovnishverma/Python-Getting-Started/blob/main/numpy_223.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Need of NumPy

**NumPy is written in mostly C and some extensions in C++**

Why Python is slow

https://github.com/lovnishverma/Python-Getting-Started/blob/main/numpy_vs_python_speed_demo.ipynb

# Dynamic Type nature of python

In [47]:
a, b = 'jjj', 8.0

#type casting

s = int(5.3)

type(s)

print(s)

5


In [42]:
type(b)

float

#NumPy

NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures. https://numpy.org/doc/stable/user/absolute_beginners.html learn about NumPy.

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.5.1


In [4]:
ls = [1,2,3,4,5,6]

print(type(ls))


arr = np.array(ls)

print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
# 1 D array in python

In [6]:
arr1d = np.array([1,2,3,4,5,6])

In [7]:
print(arr1d)

[1 2 3 4 5 6]


In [8]:
print(arr1d.ndim)

1


In [9]:
print(arr1d.size)

6


In [10]:
print(arr1d.shape)

(6,)


In [11]:
print(arr1d.dtype)

int64


# 2 D Array

In [12]:
arr2d = np.array([[1,2,3],[4,5,6]])

In [13]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [14]:
arr2d.ndim

2

In [15]:
arr2d.shape

(2, 3)

# 3 D Array

In [18]:
arr3d = np.array([[[1,2,3],[4,5,6]]])

In [17]:
arr3d.ndim

3

In [19]:
print(arr3d )

[[[1 2 3]
  [4 5 6]]]


# Special Arrays

In [27]:
# Ones array

one = np.ones((6,3))

one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
# Zeros array

z = np.zeros((6,3))

z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
# eye matrix

eye = np.eye(16)

print(eye)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


# Random no.

In [68]:
# plant seed
# np.random.seed(1)
ra = np.random.rand(3, 3)  # Random numbers between 0 and 1
print(ra)

[[0.68650093 0.83462567 0.01828828]
 [0.75014431 0.98886109 0.74816565]
 [0.28044399 0.78927933 0.10322601]]


In [69]:
# Array Indexing & Slicing

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])      # First element
print(arr[-1])     # Last element
print(arr[1:4])    # Slicing (from index 1 to 3)
print(arr[::])    # Every second element

10
50
[20 30 40]
[10 20 30 40 50]


In [70]:
print(arr)

[10 20 30 40 50]


In [75]:
print(arr[0::2]) # start:stop:step/jump

[10 30 50]


## **For 2D arrays:**

In [76]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])


print(arr2d)

[[1 2 3]
 [4 5 6]]


In [77]:
print(arr2d[0, 1])  # Row 0, Column 1
print(arr2d[:, 1])  # All rows, Column 1
print(arr2d[1, :])  # Row 1, all columns

2
[2 5]
[4 5 6]


In [79]:
print(arr2d[:,:-1])

[[1 2]
 [4 5]]


In [84]:
# Arithmetic Operations


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # Element-wise addition
print(a - b)  # Element-wise subtraction
print(a * b)  # Element-wise multiplication
print(a / b)  # Element-wise division
print(a ** 2) # Square of each element

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [88]:
# Aggregations


arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))  # Sum of elements
print(np.mean(arr)) # Mean (average)
print(np.max(arr))  # Maximum element
print(np.min(arr))  # Minimum element
print(np.std(arr))  # Standard deviation

15
3.0
5
1
1.4142135623730951


In [90]:
# Reshaping & Transposing


arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.ndim)
reshaped = arr.reshape(2, 3)
print(reshaped)

print(reshaped.ndim)

1
[[1 2 3]
 [4 5 6]]
2


In [91]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d.T)  # Transpose of matrix

[[1 4]
 [2 5]
 [3 6]]


# Stacking & Concatenation

In [93]:
# Horizontal Stacking

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.hstack((a, b)))

[1 2 3 4 5 6]


In [94]:
# Vertical Stacking

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.vstack((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]




---



# Mini Project example: Normalization

In [97]:
data = np.array([50, 100, 40, 300,  150, 200])

normalized = (data - np.min(data)) / (np.max(data) - np.min(data))

print(normalized) # Scaling

[0.03846154 0.23076923 0.         1.         0.42307692 0.61538462]


# Learn More:
https://github.com/lovnishverma/Python-Getting-Started/blob/main/numpy_official.ipynb

https://pypi.org/project/numpy/

https://numpy.org/doc/stable/user/absolute_beginners.html

https://github.com/lovnishverma/Python-Getting-Started/blob/main/numpy_mini_project.ipynb

**Project Ideas:** https://github.com/lovnishverma/Python-Getting-Started/blob/main/30%20NumPy%20Projects%20Ideas.pdf