<a href="https://colab.research.google.com/github/lovnishverma/Python-Getting-Started/blob/main/NumPy_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy**
*Lovnish Verma*

* numpy stands for numeric python
* it is very fast coz it's written in C and C++

## Introduction to NumPy


NumPy is a Python library used for numerical computations.  
It provides a powerful object: the **ndarray**, which is faster and more memory-efficient than Python lists.


# Import numpy

In [17]:
import numpy as np

In [20]:
print(np.__version__)

2.0.2


a). 1-D array

In [26]:
a1 = np.array([1,2,3,4])

print(a1)

[1 2 3 4]


b). 2-D array

In [24]:
a2 = np.array([[1,2,3,4], [5,6,7,8]])

print(a2)

[[1 2 3 4]
 [5 6 7 8]]


c). 3-D array

In [25]:
a3 = np.array([[[1,2,3,4], [5,6,7,8], [9,70,11,12]]])

print(a3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 70 11 12]]]


# Checking arr properties

In [27]:
a1.ndim # no. of dimensions btata hai

1

In [28]:
a2.ndim

2

In [29]:
a3.ndim

3



---



In [35]:
a3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 70, 11, 12]]])

In [34]:
# Shape (rows, columns)
print(a1.shape)
print(a2.shape)
print(a3.shape)

(4,)
(2, 4)
(1, 3, 4)




---



In [37]:
# Total no. of elements
print(a1.size)
print(a2.size)
print(a3.size)

4
8
12




---



In [38]:
# Data type of elements
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
int64
int64


# Special Arrays

a). Zeros Array

In [41]:
zeros = np.zeros((10,5))

print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


b). Ones array

In [42]:
ones = np.ones((10,5))

print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


c). Indentity matrix

In [44]:
identity = np.eye(10)

print(identity)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


d). Random no.

In [51]:
random = np.random.random((10,5))

print(random)

[[0.7118274  0.27986602 0.4006817  0.22506481 0.26212192]
 [0.40592541 0.11361488 0.84153585 0.72834158 0.12034389]
 [0.51992515 0.09308405 0.2669539  0.06350534 0.78060473]
 [0.12460473 0.96162152 0.11472354 0.64603384 0.81154926]
 [0.53244328 0.70497155 0.59850935 0.92306415 0.6264133 ]
 [0.49493336 0.7897743  0.84497477 0.04725736 0.64948184]
 [0.86080079 0.79432765 0.72765745 0.55205921 0.28320975]
 [0.92581073 0.95213658 0.29845963 0.64233062 0.89415638]
 [0.22014492 0.53615635 0.09122489 0.67865515 0.15750021]
 [0.94953945 0.74998128 0.41696158 0.08360451 0.69042536]]




---



# Indexing anad Slicing

In [52]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])

In [54]:
print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


In [57]:
print(arr[0]) # 1st element

40


In [58]:
print(arr[-1]) # Last element

100


In [59]:
print(arr[1:4]) # Last element

[20 30 40]


In [60]:
print(arr[4:8]) # Last element

[50 60 70 80]


In [62]:
print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


In [63]:
print(arr[::2]) # Every 2nd element

[10 30 50 70 90]


In [68]:
print(arr[2:9:3]) # start:stop:jump

[30 60 90]


For 2-d array

In [69]:
arr2d = np.array([[10,20,30,40], [50,60,70,80], [90,100,110,120]])

In [70]:
print(arr2d)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [73]:
print(arr2d[0, 2]) # row 0, column 2

30


In [74]:
print(arr2d[2, 3])

120


In [81]:
print(arr2d[1, :]) # Row 1 , all the columns

[50 60 70 80]




---



# Arithmetic Operations

In [82]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [90]:
print(a + b)
print(a - b)
print(a * b)
print(a / b) # divide
print(a ** 2) # square of each element

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]




---



# Aggregations

In [95]:
arr = np.array([1,2,3,4,5])

In [96]:
print(np.sum(arr)) # addition

15


In [97]:
print(np.mean(arr)) # average

3.0


In [98]:
print(np.max(arr)) # find maximum element in a array

5


In [99]:
print(np.min(arr)) # minimum element in a array

1


In [100]:
print(np.std(arr)) # standard deviation

1.4142135623730951




---



# Reshaping and Transposing

In [109]:
arr = np.array([1,2,3, 4,5,6])

In [110]:
print(arr)

[1 2 3 4 5 6]


In [112]:
reshaped = arr.reshape(2,3)

print(reshaped)

[[1 2 3]
 [4 5 6]]


# Traansposing

In [114]:
arr = np.array([[1,2,3], [4,5,6]])

print(arr.T) # transpose of matrix

[[1 4]
 [2 5]
 [3 6]]


# Stacking and Concetenation

**Horizontal Stacking**

In [115]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.hstack((a,b)))

[1 2 3 4 5 6]


**Verical Stacking**

In [117]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Useful Numpy fuctions

In [125]:
arr = np.array([1,2,3,4,4,5,6,6])

unique = np.unique(arr)

print(unique)

[1 2 3 4 5 6]


In [124]:
arr = np.array([1,2,7,3,8,4,4,5,6,6])

sorted = np.sort(arr)

print(sorted)

[1 2 3 4 4 5 6 6 7 8]


In [127]:
arr = np.array([1,2,7,3,8,4,4,5,6,6])

where_vals = np.where(arr == 5)

print(where_vals)

(array([7]),)


# Mini Project example: Normalization

In [129]:
data = np.array([50, 100, 150, 200])

normalized = (data - np.min(data)) / (np.max(data) - np.min(data))

print(normalized)

[0.         0.33333333 0.66666667 1.        ]
