<a href="https://colab.research.google.com/github/lovnishverma/Python-Getting-Started/blob/main/NUMPY_PANDAS_COMPLETE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note** For conciseness we’ll only be covering the key concepts within each of the
libraries with a brief introduction and code implementation. You can always refer to the
official user documents for these packages that have been well designed by the developer
community to cover a lot more in depth.


# NumPy

NumPy is the core library for scientific computing in Python. It provides a highperformance multidimensional array object, and tools for working with these arrays. It’s a
successor of Numeric package. In 2005, Travis Oliphant created NumPy by incorporating
features of the competing Numarray into Numeric, with extensive modifications. I think
the concepts and the code examples to a great extent have been explained in the simplest
form in his book Guide to NumPy. Here we’ll only be looking at some of the key NumPy
concepts that are a must or good to know in relevance to machine learning.

**Array**

A NumPy array is a collection of similar data type values, and is indexed by a tuple of
nonnegative numbers. The rank of the array is the number of dimensions, and the shape
of an array is a tuple of numbers giving the size of the array along each dimension.
We can initialize NumPy arrays from nested Python lists, and access elements using
square brackets. See Listing 2-1.


Listing 2-1. Example code for initializing NumPy array

In [229]:
import numpy as np
# Create a rank 1 array
a = np.array([0, 1, 2])
print(type(a))
# this will print(the dimension of the array
print(a.shape)
print(a[0])
print(a[1])
print(a[2])
# Change an element of the array
a[0] = 5
print(a)

<class 'numpy.ndarray'>

(3,)

0

1

2

[5 1 2]

In [230]:
# Create a rank 2 array
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)

[[0 1 2]
 [3 4 5]]

0 1 3

**Creating NumPy Array**

NumPy also provides many built-in functions to create arrays. The best way to learn this
is through examples, so let’s jump into the code. See Listing 2-2.

Listing 2-2. Creating NumPy array

In [231]:
# Create a 3x3 array of all zeros
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [232]:
# Create a 2x2 array of all ones
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [233]:
# Create a 3x3 constant array
c = np.full((3,3), 7)
c

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [234]:
# Create a 3x3 array filled with random values
d = np.random.random((3,3))
d

array([[0.60310145, 0.77825281, 0.14049056],
       [0.59043397, 0.72323741, 0.59080051],
       [0.31915944, 0.79632011, 0.74760793]])

In [235]:
# Create a 3x3 identity matrix
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [236]:
# convert list to array
f = np.array([2, 3, 1, 0])
f

array([2, 3, 1, 0])

In [237]:
# arange() will create arrays with regularly incrementing values
g = np.arange(20)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [238]:
# note mix of tuple and lists
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
h

array([[0.+0.j, 1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j, 2.+0.j]])

In [239]:
# create an array of range with float data type
i = np.arange(1, 8, dtype=float)
i

array([1., 2., 3., 4., 5., 6., 7.])

In [240]:
# linspace() will create arrays with a specified number of items which are
# spaced equally between the specified beginning and end values
j = np.linspace(2., 4., 5)
j

array([2. , 2.5, 3. , 3.5, 4. ])

In [241]:
# indices() will create a set of arrays stacked as a one-higher
# dimensioned array, one per dimension with each representing variation
# in that dimension
k = np.indices((2,2))
k

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

**Data Types**

An array is a collection of items of the same data type and NumPy supports and provides
built-in functions to construct arrays with optional arguments to explicitly specify
required datatypes.

Listing 2-3. NumPy datatypes

In [242]:
# Let numpy choose the datatype
x = np.array([0, 1])
y = np.array([2.0, 3.0])
# Force a particular datatype
z = np.array([5, 6], dtype=np.int64)
print(x.dtype, y.dtype, z.dtype)

int64 float64 int64

**Array Indexing**

NumPy offers several ways to index into arrays. Standard Python x[obj] syntax can be
used to index NumPy array, where x is the array and obj is the selection.
There are three kinds of indexing available:
• Field access
• Basic slicing
• Advanced indexing

**Field Access**

If the ndarray object is a structured array, the fields of the array can be accessed by
indexing the array with strings, dictionary like. Indexing x[‘field-name’] returns a new
view to the array, which is of the same shape as x, except when the field is a subarray, but
of data type x.dtype[‘field-name’] and contains only the part of the data in the specified
field. See Listing 2-4.

Listing 2-4. Field access

In [243]:
x = np.zeros((3, 3), dtype=[('a', np.int32), ('b', np.float64, (3, 3))])

print("x['a'].shape: ", x['a'].shape)
print("x['a'].dtype: ", x['a'].dtype)
print("x['b'].shape: ", x['b'].shape)
print("x['b'].dtype: ", x['b'].dtype)

x['a'].shape: 
(3, 3)

x['a'].dtype:  int32

x['b'].shape: 
(3, 3, 3, 3)

x['b'].dtype:  float64

**Basic Slicing**

NumPy arrays can be sliced, similar to lists. You must specify a slice for each dimension of
the array as the arrays may be multidimensional.
The basic slice syntax is i: j: k, where i is the starting index, j is the stopping index,
and k is the step and k is not equal to 0. This selects the m elements in the corresponding
dimension, with index values i, i + k, …,i + (m - 1) k where m = q + (r not equal to 0) and q
and r are the quotient and the remainder is obtained by dividing j - i by k: j - i = q k + r, so
that i + (m - 1) k < j. See Listing 2-5.

Listing 2-5. Basic slicing

In [244]:
x = np.array([5, 6, 7, 8, 9])
x[1:7:2]

array([6, 8])

Negative k makes stepping go toward smaller indices. Negative i and j are
interpreted as n + i and n + j where n is the number of elements in the
corresponding dimension.

In [245]:
print(x[-2:5])
print(x[-1:1:-1])

[8 9]

[9 8 7]

If n is the number of items in the dimension being sliced. Then if i is not
given then it defaults to 0 for k > 0 and n - 1 for k < 0. If j is not given
it defaults to n for k > 0 and -1 for k < 0. If k is not given it defaults
to 1. Note that :: is the same as : and means select all indices along this
axis.

In [246]:
x[4:]

array([9])

If the number of objects in the selection tuple is less than N, then : is
assumed for any subsequent dimensions.

Listing 2-6. Basic slicing

In [247]:
y = np.array([[[1], [2], [3]],
              [[4], [5], [6]]])

print("Shape of y: ", y.shape)
y[1:3]

Shape of y: 
(2, 3, 1)

array([[[4],
        [5],
        [6]]])

Ellipsis expand to the number of : objects needed to make a selection tuple
of the same length as x.ndim. There may only be a single ellipsis present.


In [248]:
x[...,0]

array(5)

In [249]:
# Create a rank 2 array with shape (3, 4)
a = np.array([[5, 6, 7, 8],
              [1, 2, 3, 4],
              [9, 10, 11, 12]])

print("Array a:", a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
# [6 7]]
b = a[:2, 1:3]
print("Array b:\n", b)

Array a: [[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]

Array b:
 [[6 7]
 [2 3]]

A slice of an array is a view into the same data, so modifying itwill modify
the original array.

In [250]:
print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])

6

77

Middle row array can be accessed in two ways. 1) Slices along with integer
indexing will result in an arry of lower rank. 2) Using only slices will
result in same rank array.

Example code:

In [251]:
row_r1 = a[1, :]   # Rank 1 view of the second row of a
row_r2 = a[1:2, :] # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)  # Prints "[1 2 3 4] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[1 2 3 4]] (1, 4)"

[1 2 3 4]
(4,)

[[1 2 3 4]]
(1, 4)

In [252]:
# Accessing columns of an array
col_r1 = a[:, 1]    # Rank 1 view of the second column
col_r2 = a[:, 1:2]  # Rank 2 view of the second column

print(col_r1, col_r1.shape)  # Prints "[6 2 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[6] [2] [10]] (3, 1)"

[77  2 10]
(3,)

[[77]
 [ 2]
 [10]]
(3, 1)

**Advanced Indexing**

Integer array indexing: Integer array indexing allows you to construct random arrays and
other arrays. See Listing 2-7.

Listing 2-7. Advanced indexinga = np.array([[1,2], [3, 4]])

In [253]:
# An example of integer array indexing.
# The returned array will have shape (2,) and
print(a[[0, 1], [0, 1]])
# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1]]))

[5 2]

[5 2]

In [254]:
# When using integer array indexing, you can reuse the same element from the source array:
print(a[[0, 0], [1, 1]])

[77 77]

In [255]:
# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[77 77]

Boolean array indexing: This is useful to pick a random element from an array, which
is often used for filtering elements that satisfy a given condition. See Listing 2-8.

Listing 2-8. Boolean array indexing

In [256]:
# Boolean array indexing: Useful to pick elements from an array that satisfy a condition
a = np.array([[1, 2], [3, 4], [5, 6]])
# Find the elements of a that are bigger than 2
print(a > 2)
# Get the actual values
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]

[3 4 5 6]

Basic mathematical functions are available as operators and also as functions in NumPy.
It operates element-wise on an array. See Listing 2-9.

Listing 2-9. Array math

In [257]:
# Element-wise operations
x = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([[7, 8], [9, 10], [11, 12]])

In [258]:
# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 8 10]
 [12 14]
 [16 18]]

[[ 8 10]
 [12 14]
 [16 18]]

In [259]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-6 -6]
 [-6 -6]
 [-6 -6]]

[[-6 -6]
 [-6 -6]
 [-6 -6]]

In [260]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 7 16]
 [27 40]
 [55 72]]

[[ 7 16]
 [27 40]
 [55 72]]

In [261]:
# Elementwise division; both produce the array
print(x / y)
print(np.divide(x, y))

[[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]

[[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]

In [262]:
# Elementwise square root; produces the array
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]

We can use the “dot” function to calculate inner products of vectors or to multiply
matrices or multiply a vector by a matrix. See Listing 2-10.

Listing 2-10. Array math (continued)

In [263]:
# Dot product examples
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
a_vec = np.array([9, 10])
b_vec = np.array([11, 12])

In [264]:
# Inner product of vectors
print(a_vec.dot(b_vec))
print(np.dot(a_vec, b_vec))

219

219

In [265]:
# Matrix / vector product
print(x.dot(a_vec))
print(np.dot(x, a_vec))

[29 67]

[29 67]

In [266]:
# Matrix / matrix product
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]

NumPy provides many useful functions for performing computations on arrays. One
of the most useful is sum.

See Listing 2-11.

Listing 2-11. Sum function

In [267]:
# Sum function
x = np.array([[1, 2], [3, 4]])

In [268]:
# Compute sum of all elements
print(np.sum(x))

10

In [269]:
# Compute sum of each column
print(np.sum(x, axis=0))

[4 6]

In [270]:
# Compute sum of each row
print(np.sum(x, axis=1))

[3 7]

Transpose is one of the common operations often performed on matrix, which can
be achieved using the T attribute of an array object.

See Listing 2-12.

In [271]:
# Transpose
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T)

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]

In [272]:
# Note that taking the transpose of a rank 1 array does nothing
v = np.array([1, 2, 3])
print(v)
print(v.T)

[1 2 3]

[1 2 3]

**Broadcasting**

Broadcasting enables arithmetic operations to be performed between different shaped
arrays. Let’s look at a simple example of adding a constant vector to each row of a matrix.
See Listing 2-13.

Listing 2-13. Broadcasting

In [273]:
# Broadcasting
# Adding a vector to each row of a matrix
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v = np.array([1, 0, 1])

In [274]:
# Add the vector v to each row of the matrix a with an explicit loop
b = np.empty_like(a)
for i in range(3):
    b[i, :] = a[i, :] + v
print(b)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]

If you have to perform the above operation on a large matrix, the through loop in
Python could be slow. Let’s look at an alternative approach. See Listing 2-14.

Listing 2-14. Broadcasting for large matrix

In [275]:
# Stack 3 copies of v on top of each other
# Using np.tile to create a repeated matrix
vv = np.tile(v, (3, 1))
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]]

In [276]:
# Add a and vv elementwise
b = a + vv
print(b)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]

Now let’s see in Listing 2-15 how the above can be achieved using NumPy
broadcasting.

Listing 2-15. Broadcasting using NumPy

In [277]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([1, 0, 1])
# Add v to each row of a using broadcasting
b = a + v
print(b)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]

Now let’s look at some applications of broadcasting in Listing 2-16.

Listing 2-16. Applications of broadcasting

In [278]:
# Applications of broadcasting
# Compute outer product of vectors
v = np.array([1, 2, 3])  # shape (3,)
w = np.array([4, 5])     # shape (2,)
# Reshape v to (3,1) and broadcast against w to get (3,2)
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]

In [279]:
# Add a vector to each row of a matrix
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x + v)

[[2 4 6]
 [5 7 9]]

In [280]:
# Add a vector to each column of a matrix
# Using transpose and broadcasting
print((x.T + w).T)
# Alternative: reshape w to (2,1)
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]

[[ 5  6  7]
 [ 9 10 11]]

In [281]:
# Multiply a matrix by a constant
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]

Broadcasting typically makes your code more concise and faster, so you should strive
to use it where possible.

# **Pandas**

Python has always been great for data munging; however it was not great for analysis
compared to databases using SQL or Excel or R data frames. Pandas are an open source
Python package providing fast, flexible, and expressive data structures designed to make
working with “relational” or “labeled” data both easy and intuitive. Pandas were developed
by Wes McKinney in 2008 while at AQR Capital Management out of the need for a high
performance, flexible tool to perform quantitative analysis on financial data. Before
leaving AQR he was able to convince management to allow him to open source the library.
Pandas are well suited for tabular data with heterogeneously typed columns, as in an
SQL table or Excel spreadsheet.

# Data Structures

Pandas introduces two new data structures to Python – Series and DataFrame, both of
which are built on top of NumPy (this means it’s fast).
Series
This is a one-dimensional object similar to column in a spreadsheet or SQL table. By
default each item will be assigned an index label from 0 to N. See Listing 2-17.

Listing 2-17. Creating a pandas series

In [282]:
import pandas as pd

In [289]:
# creating a series by passing a list of values, and a custom index label.
# Note that the labeled index reference for each row and it can have duplicate values
s = pd.Series([1,2,3,np.nan,5,6], index=['A','B','C','D','E','F'])
print(s)

A    1.0
B    2.0
C    3.0
D    NaN
E    5.0
F    6.0
dtype: float64

**DataFrame**

It is a two-dimensional object similar to a spreadsheet or an SQL table. This is the most
commonly used pandas object. See Listing 2-18.

Listing 2-18. Creating a pandas dataframe

In [290]:
data = {'Gender': ['F', 'M', 'M'],'Emp_ID': ['E01', 'E02',
'E03'], 'Age': [25, 27, 25]}
# We want the order the columns, so lets specify in columns parameter
df = pd.DataFrame(data, columns=['Emp_ID','Gender', 'Age'])
print(df)

Emp_ID Gender  Age
0    E01      F   25
1    E02      M   27
2    E03      M   25

Reading and Writing Data
We’ll see three commonly used file formats: csv, text file, and Excel in Listing 2-19.

Listing 2-19. Reading / writing data from csv, text, Excel



```
# Reading
df=pd.read_csv('Data/mtcars.csv') # from csv
df=pd.read_csv('Data/mtcars.txt', sep='\t') # from text file
df=pd.read_excel('Data/mtcars.xlsx','Sheet2') # from Excel

# reading from multiple sheets of same Excel into different dataframes
xlsx = pd.ExcelFile('file_name.xls')
sheet1_df = pd.read_excel(xlsx, 'Sheet1')
sheet2_df = pd.read_excel(xlsx, 'Sheet2')

# writing
# index = False parameter will not write the index values, default is True
df.to_csv('Data/mtcars_new.csv', index=False)
df.to_csv('Data/mtcars_new.txt', sep='\t', index=False)
df.to_excel('Data/mtcars_new.xlsx',sheet_name='Sheet1', index = False)
```



■ Note Write will by default overwrite any existing file with the same name.

**Basic Statistics Summary**

Pandas has some built-in functions to help us to get better understanding of data using
basic statistical summary methods. See Listings 2-20, 2-21, and 2-22.
describe()- will returns the quick stats such as count, mean, std (standard
deviation), min, first quartile, median, third quartile, max on each column
of the dataframe

Listing 2-20. Basic statistics on dataframe

In [295]:
df = pd.read_csv("https://raw.githubusercontent.com/lovnishverma/datasets/refs/heads/main/iris_default.csv")

In [296]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

**cov()** - Covariance indicates how two variables are related. A positive
covariance means the variables are positively related, while a negative
covariance means the variables are inversely related. Drawback of covariance
is that it does not tell you the degree of positive or negative relation

Listing 2-21. Creating covariance on dataframe

In [297]:
df.cov()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           0.685694         -0.042434           1.274315   
sepal width (cm)           -0.042434          0.189979          -0.329656   
petal length (cm)           1.274315         -0.329656           3.116278   
petal width (cm)            0.516271         -0.121639           1.295609   

                   petal width (cm)  
sepal length (cm)          0.516271  
sepal width (cm)          -0.121639  
petal length (cm)          1.295609  
petal width (cm)           0.581006

**corr()** - Correlation is another way to determine how two variables are
related. In addition to telling you whether variables are positively or
inversely related, correlation also tells you the degree to which the
variables tend to move together. When you say that two items correlate, you
are saying that the change in one item effects a change in another item. You
will always talk about correlation as a range between -1 and 1. In the below
example code, petal length is 87% positively related to sepal length that
means a change in petal length results in a positive 87% change to sepal
lenth and vice versa.

Listing 2-22. Creating correlation matrix on dataframe

In [298]:
df.corr()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)          0.817941  
sepal width (cm)          -0.366126  
petal length (cm)          0.962865  
petal width (cm)           1.000000

**Viewing Data**

The Pandas dataframe comes with built-in functions to view the contained data. See
Table 2-2.

Table 2-2. Pandas view function

| **Description**                               | **Syntax / Example**                                                                               |
| --------------------------------------------- | -------------------------------------------------------------------------------------------------- |
| Convert string to date series                 | `pd.to_datetime(pd.Series(['2017-04-01','2017-04-02','2017-04-03']))`                              |
| Rename a specific column                      | `df.rename(columns={'old_columnname':'new_columnname'}, inplace=True)`                             |
| Rename all columns of DataFrame               | `df.columns = ['col1_new_name','col2_new_name', …]`                                                |
| Flag duplicates                               | `df.duplicated()`                                                                                  |
| Drop duplicates                               | `df = df.drop_duplicates()`                                                                        |
| Drop duplicates in specific column            | `df.drop_duplicates(['column_name'])`                                                              |
| Drop duplicates but retain first/last         | `df.drop_duplicates(['column_name'], keep='first')` # use `'last'` to retain last occurrence       |
| Create new column from existing column        | `df['new_column_name'] = df['existing_column_name'] + 5`                                           |
| Create new column from two columns            | `df['new_column_name'] = df['existing_column1'] + '_' + df['existing_column2']`                    |
| Add a list or new column to DataFrame         | `df['new_column_name'] = pd.Series(mylist)`                                                        |
| Drop missing rows/columns                     | `df.dropna()`                                                                                      |
| Replace all missing values with 0             | `df.fillna(value=0)`                                                                               |
| Forward/backward fill missing values          | `df.fillna(method='ffill', inplace=True, limit=1)` # forward fill; use `'bfill'` for backward fill |
| Check missing value condition                 | `pd.isnull(df)` # returns Boolean True/False for each cell                                         |
| Replace missing values with column mean       | `mean = df['column_name'].mean(); df['column_name'].fillna(mean)`                                  |
| Return mean for each column                   | `df.mean()`                                                                                        |
| Return max for each column                    | `df.max()`                                                                                         |
| Return min for each column                    | `df.min()`                                                                                         |
| Return sum for each column                    | `df.sum()`                                                                                         |
| Return count for each column                  | `df.count()`                                                                                       |
| Return cumulative sum for each column         | `df.cumsum()`                                                                                      |
| Apply a function along any axis               | `df.apply(np.cumsum)`                                                                              |
| Iterate over a series                         | `df['column_name'].map(lambda x: 1+x)` # adds 1 to each element                                    |
| Apply a function to each element of DataFrame | `func = lambda x: x + 1; df.applymap(func)` # adds 1 to every element                              |

---


**Merge/Join**

Pandas provide various facilities for easily combining together Series, DataFrame,
and Panel objects with various kinds of set logic for the indexes and relational algebra
functionality in the case of join merge-type operations. See Figure 2-27.

Listing 2-23. Concat or append operation

In [300]:
data = {
 'emp_id': ['1', '2', '3', '4', '5'],
 'first_name': ['Jason', 'Andy', 'Allen', 'Alice', 'Amy'],
 'last_name': ['Larkin', 'Jacob', 'A', 'AA', 'Jackson']}

df_1 = pd.DataFrame(data, columns = ['emp_id', 'first_name', 'last_name'])

data = {
 'emp_id': ['4', '5', '6', '7'],
 'first_name': ['Brian', 'Shize', 'Kim', 'Jose'],
 'last_name': ['Alexander', 'Suma', 'Mike', 'G']}

df_2 = pd.DataFrame(data, columns = ['emp_id', 'first_name', 'last_name'])

In [303]:
# Using concat
df = pd.concat([df_1, df_2])
print(df)

emp_id first_name  last_name
0      1      Jason     Larkin
1      2       Andy      Jacob
2      3      Allen          A
3      4      Alice         AA
4      5        Amy    Jackson
0      4      Brian  Alexander
1      5      Shize       Suma
2      6        Kim       Mike
3      7       Jose          G

In [308]:
# Join the two dataframes along columns
pd.concat([df_1, df_2], axis=1)

emp_id first_name last_name emp_id first_name  last_name
0      1      Jason    Larkin      4      Brian  Alexander
1      2       Andy     Jacob      5      Shize       Suma
2      3      Allen         A      6        Kim       Mike
3      4      Alice        AA      7       Jose          G
4      5        Amy   Jackson    NaN        NaN        NaN

Listing 2-24. Merge two dataframes

In [309]:
# Merge two dataframes based on the emp_id value
# in this case only the emp_id's present in both table will be joined
pd.merge(df_1, df_2, on='emp_id')

emp_id first_name_x last_name_x first_name_y last_name_y
0      4        Alice          AA        Brian   Alexander
1      5          Amy     Jackson        Shize        Suma

**Join**

Pandas offer SQL style merges as well.
Left join produces a complete set of records from Table A, with the matching records
where available in Table B. If there is no match, the right side will contain null.

■ Note Note that you can suffix to avoid duplicate; if not provided it will automatically add
x to the Table A and y to Table B. See Listings 2-25 and 2-26.



Listing 2-25. Left join two dataframes

In [310]:
# Left join
print(pd.merge(df_1, df_2, on='emp_id', how='left'))

emp_id first_name_x last_name_x first_name_y last_name_y
0      1        Jason      Larkin          NaN         NaN
1      2         Andy       Jacob          NaN         NaN
2      3        Allen           A          NaN         NaN
3      4        Alice          AA        Brian   Alexander
4      5          Amy     Jackson        Shize        Suma

In [311]:
# Merge while adding a suffix to duplicate column names of both table
print(pd.merge(df_1, df_2, on='emp_id', how='left', suffixes=('_left', '_right')))

emp_id first_name_left last_name_left first_name_right last_name_right
0      1           Jason         Larkin              NaN             NaN
1      2            Andy          Jacob              NaN             NaN
2      3           Allen              A              NaN             NaN
3      4           Alice             AA            Brian       Alexander
4      5             Amy        Jackson            Shize            Suma

Right join - Right join produces a complete set of records from Table B,
with the matching records where available in Table A. If there is no match,
the left side will contain null.

Listing 2-26. Right join two dataframes

In [313]:
# Right join
pd.merge(df_1, df_2, on='emp_id', how='right')

emp_id first_name_x last_name_x first_name_y last_name_y
0      4        Alice          AA        Brian   Alexander
1      5          Amy     Jackson        Shize        Suma
2      6          NaN         NaN          Kim        Mike
3      7          NaN         NaN         Jose           G

Inner Join - Inner join produces only the set of records that match in both Table A
and Table B. See Listing 2-27

Listing 2-27. Inner join two dataframespd.merge(df_1, df_2, on=‘emp_id’, how=‘inner’)

In [314]:
# Inner Join
pd.merge(df_1, df_2, on='emp_id', how='inner')

emp_id first_name_x last_name_x first_name_y last_name_y
0      4        Alice          AA        Brian   Alexander
1      5          Amy     Jackson        Shize        Suma

Outer Join - Full outer join produces the set of all records in Table A and Table B, with
matching records from both sides where available. If there is no match, the missing side
will contain null as in Listing 2-28.

Listing 2-28. Outer join two dataframes

In [315]:
pd.merge(df_1, df_2, on='emp_id', how='outer')

emp_id first_name_x last_name_x first_name_y last_name_y
0      1        Jason      Larkin          NaN         NaN
1      2         Andy       Jacob          NaN         NaN
2      3        Allen           A          NaN         NaN
3      4        Alice          AA        Brian   Alexander
4      5          Amy     Jackson        Shize        Suma
5      6          NaN         NaN          Kim        Mike
6      7          NaN         NaN         Jose           G

**Grouping**

Grouping involves one or more of the following steps:
• Splitting the data into groups based on some criteria,
• Applying a function to each group independently,
• Combining the results into a data structure (see Listing 2-29).

Listing 2-29. Grouping operation

In [327]:
# Create the DataFrame
df = pd.DataFrame({
    'Name': ['jack', 'jane', 'jack', 'jane', 'jack', 'jane', 'jack', 'jane'],
    'State': ['SFO', 'SFO', 'NYK', 'CA', 'NYK', 'NYK', 'SFO', 'CA'],
    'Grade': ['A', 'A', 'B', 'A', 'C', 'B', 'C', 'A'],
    'Age': np.random.uniform(24, 50, size=8),
    'Salary': np.random.uniform(3000, 5000, size=8)
})

In [328]:
# Display the DataFrame
print(df)

Name State Grade        Age       Salary
0  jack   SFO     A  33.817568  3802.735981
1  jane   SFO     A  26.984826  3145.011619
2  jack   NYK     B  39.536996  3159.596474
3  jane    CA     A  32.932836  4149.761683
4  jack   NYK     C  31.161251  3191.318096
5  jane   NYK     B  24.274891  4846.425250
6  jack   SFO     C  26.779990  4050.345542
7  jane    CA     A  27.536945  4477.519257

In [330]:
# Find max age and salary by Name / State
# with groupby, we can use all aggregate functions such as min, max, mean, count, cumsum
df.groupby(['Name','State']).max()

Grade        Age       Salary
Name State                              
jack NYK       C  39.536996  3191.318096
     SFO       C  33.817568  4050.345542
jane CA        A  32.932836  4477.519257
     NYK       B  24.274891  4846.425250
     SFO       A  26.984826  3145.011619

**Pivot Tables**

Pandas provides a function ‘pivot_table’ to create MS-Excel spreadsheet style pivot tables.
It can take following arguments:
• data: DataFrame object,
• values: column to aggregate,
• index: row labels,
• columns: column labels,
• aggfunc: aggregation function to be used on values, default is
NumPy.mean (see Listing 2-30).

Listing 2-30. Pivot tables

In [331]:
# by state and name find mean age for each grade
pd.pivot_table(df, values='Age', index=['State', 'Name'], columns=['Grade'])

Grade               A          B          C
State Name                                 
CA    jane  30.234891        NaN        NaN
NYK   jack        NaN  39.536996  31.161251
      jane        NaN  24.274891        NaN
SFO   jack  33.817568        NaN  26.779990
      jane  26.984826        NaN        NaN

In [333]:
print("[bold green] THANK YOU, MADE WITH LOT'S OF LOVE BY LOVNISH VERMA [/bold green]")

 THANK YOU, MADE WITH LOT'S OF LOVE BY LOVNISH VERMA 



---

